auth:
  # see https://backstage.io/docs/auth/ to learn about auth providers
  providers:
    # See https://backstage.io/docs/auth/guest/provider
    guest: {}
    github:
      development:
        clientId: 'Ov23li2iy6AbnA9WIr37'
        clientSecret: 'b0732aefe31ff86249a9cc5d1c1c5560134a92d3'
        # signIn:
        #   resolvers:
            # Matches the GitHub username with the Backstage user entity name.
            # See https://backstage.io/docs/auth/github/provider#resolvers for more resolvers.
            # - resolver: usernameMatchingUserEntityName
            # - resolver: customAuthResolver
integrations:
  github:
    - host: github.com
      # This is a Personal Access Token or PAT from GitHub. You can find out how to generate this token, and more information
      # about setting up the GitHub integration here: https://backstage.io/docs/integrations/github/locations#configuration
      token: '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'

backend:
  reading:
    allow:
      - host: 'gist.githubusercontent.com/'
      - host: 'github.com'
  database:
    client: pg
    connection:
      host: '127.0.0.1'
      port: 5432
      user: postgres

