apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: pd-admin
  description: The administrators group
spec:
  type: role
  profile:
    displayName: Administrators
    email: pb-admin@example.com
    picture: https://example.com/groups/bu-infrastructure.jpeg
  children: [backstage, other]
  members: [jdoe]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: backstage
  description: Backstage
spec:
  type: business-unit
  profile:
    displayName: Backstage group
    email: backstage@example.com
    picture: https://example.com/groups/bu-infrastructure.jpeg
  parent: infrastructure
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: other
  description: Other
spec:
  type: business-unit
  profile:
    displayName: Other group
    email: other@example.com
    picture: https://example.com/groups/bu-infrastructure.jpeg
  parent: infrastructure
  children: []
  members: [paulb]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: infrastructure
  description: Infrastructure
spec:
  type: business-unit
  profile:
    displayName: Infrastructure group
    email: infra@example.com
  children: []
