apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: pb-admins
  description: The infra business unit
spec:
  type: team
  profile:
    displayName: PB-Administrator
    email: infrastructure@example.com
    picture: https://example.com/groups/bu-infrastructure.jpeg
  parent: ops
  children: [backstage, other]
  members: [jdoe]
