apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: minikube-cluster
  annotations:
    kubernetes.io/api-server: 'https://127.0.0.1:34531'
    kubernetes.io/api-server-certificate-authority: # base64-encoded CA
    kubernetes.io/auth-provider: 'oidc'
    kubernetes.io/oidc-token-provider: 'microsoft'
    kubernetes.io/skip-metrics-lookup: 'true'
spec:
  type: kubernetes-cluster
  owner: user:guest
